name: Maven Build and Publish

on:
  push:
    branches:
      - main

jobs:
    
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2       
        with:
            distribution: 'microsoft'
            java-version: '17'

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./commons-utils

  publish:
        needs: [build]
        name: "Publish"
        runs-on: ubuntu-latest    
        
        environment:
            name: PROD
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up JDK
              uses: actions/setup-java@v2       
              with:
                distribution: 'microsoft'
                java-version: '17'
                                
            - name: Publish to GitHub Maven Repository
              run: |
                CWD=$(pwd)
                echo "${CWD}"
                whoami
                mvn deploy -DskipTests --settings ../settings.xml
              env:
                MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                MAVEN_TOKEN: ${{ secrets.MAVEN_PASSWORD }}
              working-directory: ./commons-utils            


